In [6]:
import sys
!{sys.executable} -m pip install numpy


In [7]:
import sys
!{sys.executable} -m pip install --upgrade pip


In [8]:
import pip
print(pip.__version__)


25.3


In [9]:
import numpy as np
a = np.array([1, 2, 3, 4, 5])
print(a)

[1 2 3 4 5]


In [10]:
import numpy as np
print(np.__version__)
print(np.array([1, 2, 3, 4, 5]))


2.4.0
[1 2 3 4 5]


In [32]:
A3=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print(A3[0::,0:2])
print(A3[0::2,1:4:2])
print(A3[-1:-3:-1,-2:-5:-2])
print(A3[0::2,-3:-5:-1])
print(A3[1::,2:4])

[[ 1  2]
 [ 6  7]
 [11 12]]
[[ 2  4]
 [12 14]]
[[14 12]
 [ 9  7]]
[[ 3  2]
 [13 12]]
[[ 8  9]
 [13 14]]


In [33]:
D=np.array([ [[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]], [[13,14,15],[16,17,18]] ])
print('-----------')
print(D.shape)
print('----------------')
print(D[0::,0::,1::])
print("--------------")
print(D[-1:-3:-1,-1:-3:-1,-2::-1])
print('-----------')
print(D[0::2,0:1,0:2])
print("----------")
print(D[1::,0::,0:2:])
print("============")
print(D[0::,1::,1::])

-----------
(3, 2, 3)
----------------
[[[ 2  3]
  [ 5  6]]

 [[ 8  9]
  [11 12]]

 [[14 15]
  [17 18]]]
--------------
[[[17 16]
  [14 13]]

 [[11 10]
  [ 8  7]]]
-----------
[[[ 1  2]]

 [[13 14]]]
----------
[[[ 7  8]
  [10 11]]

 [[13 14]
  [16 17]]]
[[[ 5  6]]

 [[11 12]]

 [[17 18]]]


In [13]:
A2=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,12,13]]])
print(A2.ndim)

3


In [14]:
A1=np.array([1,2,3,4,5,6,7,8,9,10])
print(A1[::-1])
print(A1[-1:-10:-3])
print(A1[1::2])
print(A1[-3:-10:-3])

[10  9  8  7  6  5  4  3  2  1]
[10  7  4]
[ 2  4  6  8 10]
[8 5 2]


In [24]:
A2=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(A2[1,1])
print(A2[-2,-2])
print(A2[0::,0:2])
print(A2[-1:-3:-1,-1:-3:-1])
print(A2[-1::-1,-1::])
print(A2[-1::-1,-1:-3:-1])

5
5
[[1 2]
 [4 5]
 [7 8]]
[[9 8]
 [6 5]]
[[9]
 [6]
 [3]]
[[9 8]
 [6 5]
 [3 2]]


In [34]:
D=np.array([1,2,3,4,5,6,7,8,9,10,11,12])

f1=D.reshape(2,6)
print(f1)

f2=D.reshape(6,2)
print(f2)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [36]:
D=np.array([ [[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]], [[13,14,15],[16,17,18]] ])
print(D.shape)
f1=D.reshape(6,3)
f2=D.reshape(3,6)
f3=D.reshape(3,6,1)
f4=D.reshape(6,3,1)
f5=D.reshape(9,2,-1)
f6=D.reshape(9,2,1)
f7=D.reshape(18,1,1)
print(f1)
print('-----------')
print(f2)
print('-------------------')
print(f3)
print('-------------')
print(f4)
print('--------------')
print(f5)
print('----------------')
print(f6)
print("--------------")
print(f7)
print("============")
print(D.shape)
print("**************")

##Falttening
f=D.reshape(-1)
print(f)

(3, 2, 3)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
-----------
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]
-------------------
[[[ 1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]
  [ 6]]

 [[ 7]
  [ 8]
  [ 9]
  [10]
  [11]
  [12]]

 [[13]
  [14]
  [15]
  [16]
  [17]
  [18]]]
-------------
[[[ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]]

 [[ 7]
  [ 8]
  [ 9]]

 [[10]
  [11]
  [12]]

 [[13]
  [14]
  [15]]

 [[16]
  [17]
  [18]]]
--------------
[[[ 1]
  [ 2]]

 [[ 3]
  [ 4]]

 [[ 5]
  [ 6]]

 [[ 7]
  [ 8]]

 [[ 9]
  [10]]

 [[11]
  [12]]

 [[13]
  [14]]

 [[15]
  [16]]

 [[17]
  [18]]]
----------------
[[[ 1]
  [ 2]]

 [[ 3]
  [ 4]]

 [[ 5]
  [ 6]]

 [[ 7]
  [ 8]]

 [[ 9]
  [10]]

 [[11]
  [12]]

 [[13]
  [14]]

 [[15]
  [16]]

 [[17]
  [18]]]
--------------
[[[ 1]]

 [[ 2]]

 [[ 3]]

 [[ 4]]

 [[ 5]]

 [[ 6]]

 [[ 7]]

 [[ 8]]

 [[ 9]]

 [[10]]

 [[11]]

 [[12]]

 [[13]]

 [[14]]

 [[15]]

 [[16]]

 [[17]]

 [[18]]]
(3, 2, 3)
**************
[ 1  2  3  4  5

In [37]:
#array
a=np.array([1,2,3,45])
for i in a:
    print(i)

a=np.array([[1,2,3],[4,5,6]])
for i in a:
    for j in i:
        print(j)

a=np.array([[[1,2,3],[4,5,6]]])
for i in a:
    for j in i:
        for k in j:
            print(k)

1
2
3
45
1
2
3
4
5
6
1
2
3
4
5
6


In [41]:
#Random
from numpy import random
x=random.randint(1,51,size=(3,5))
print(x)

[[ 9 12 49 10 40]
 [44 41 19 48  1]
 [16 48  4 15  3]]


In [43]:
x=random.randint(100)
print(x)

84


In [44]:
x=random.randint(1,101)
print(x)

76


In [53]:
x=random.randint(0,1)
print(x)

0
